/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.jetbrains.kotlin.kotlin.stdlib.jdk8)
    api(libs.org.jetbrains.kotlin.kotlin.reflect)
    api(libs.org.jetbrains.kotlinx.kotlinx.coroutines.core)
    api(libs.io.dvlopt.linux.i2c)
    api(libs.io.github.oshai.kotlin.logging.jvm)
    api(libs.ch.qos.logback.logback.classic)
    api(libs.org.jetbrains.exposed.exposed.core)
    api(libs.org.jetbrains.exposed.exposed.kotlin.datetime)
    api(libs.org.apache.commons.commons.lang3)
    api(libs.org.xerial.sqlite.jdbc)
    api(libs.io.ktor.ktor.client.cio.jvm)
    api(libs.io.ktor.ktor.client.content.negotiation.jvm)
    api(libs.io.ktor.ktor.serialization.kotlinx.json.jvm)
    api(libs.org.jetbrains.kotlinx.kotlinx.datetime.jvm)
    api(libs.org.jetbrains.kotlinx.kotlinx.serialization.json.jvm)
    runtimeOnly(libs.org.jetbrains.exposed.exposed.jdbc)
    testImplementation(libs.org.jetbrains.kotlin.kotlin.test.junit)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.params)
    testImplementation(libs.com.thedeanda.lorem)
    testImplementation(libs.org.assertj.assertj.core)
    testImplementation(libs.io.mockk.mockk.jvm)
    testImplementation(libs.de.jollyday.jollyday)
}

group = "eu.slomkowski.octoglow"
version = "1.0-SNAPSHOT"
description = "octoglowd"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
