[package]
name = "octoglowd"
version = "0.1.0"
authors = ["Michał Słomkowski <m.slomkowski@gmail.com>"]

[dependencies]
i2cdev = "0.4.0"
chrono = "0.4"
actix = "0.5"
image = "0.19"
futures = "0.2.1"
byteorder = "1.2"
