[package]
name = "octoglowd"
version = "0.1.0"
authors = ["Michał Słomkowski <m.slomkowski@gmail.com>"]

[dependencies]
actix = "0.5"
futures = "0.1"
i2cdev = "0.4.0"
chrono = "0.4"
image = "0.19"
byteorder = "1.2"
