package eu.slomkowski.octoglow.octoglowd.calendar

import kotlinx.datetime.LocalDate

data class Ndr(
    val day: Int,
    val month: Int,
    val names: Set<String>
) {
    init {
        require(day in (1..31))
        require(month in (1..12))
        require(names.isNotEmpty())
    }

    constructor(day: Int, month: Int, vararg names: String) : this(day, month, names.toSet())
}

private val polishNameDays = listOf(
    Ndr(1, 1, "Mieszka", "Mieczysława", "Marii"),
    Ndr(2, 1, "Izydora", "Bazylego", "Grzegorza"),
    Ndr(3, 1, "Arlety", "Genowefy", "Danuty"),
    Ndr(4, 1, "Tytusa", "Anieli", "Eugeniusza"),
    Ndr(5, 1, "Hanny", "Szymona", "Edwarda"),
    Ndr(6, 1, "Kacpra", "Melchiora", "Baltazara"),
    Ndr(7, 1, "Juliana", "Lucjana", "Rajmunda"),
    Ndr(8, 1, "Seweryna", "Mścisława", "Juliusza"),
    Ndr(9, 1, "Marceliny", "Marianny", "Juliana"),
    Ndr(10, 1, "Wilhelma", "Dobrosława", "Danuty"),
    Ndr(11, 1, "Honoraty", "Teodozjusza", "Matyldy"),
    Ndr(12, 1, "Grety", "Arkadiusza", "Rajmunda"),
    Ndr(13, 1, "Bogumiły", "Weroniki", "Hilarego"),
    Ndr(14, 1, "Feliksa", "Domosława", "Niny"),
    Ndr(15, 1, "Pawła", "Arnolda", "Izydora"),
    Ndr(16, 1, "Marcelego", "Włodzimierza", "Waldemara"),
    Ndr(17, 1, "Antoniego", "Rościsława", "Jana"),
    Ndr(18, 1, "Piotra", "Małgorzaty"),
    Ndr(19, 1, "Henryka", "Mariusza", "Marty"),
    Ndr(20, 1, "Fabiana", "Sebastiana"),
    Ndr(21, 1, "Agnieszki", "Jarosława"),
    Ndr(22, 1, "Anastazego", "Wincentego"),
    Ndr(23, 1, "Ildefonsa", "Rajmunda"),
    Ndr(24, 1, "Felicji", "Franciszka", "Rafała"),
    Ndr(25, 1, "Pawła", "Miłosza", "Elwiry"),
    Ndr(26, 1, "Tymoteusza", "Michała", "Tytusa"),
    Ndr(27, 1, "Przybysława", "Anieli", "Jerzego"),
    Ndr(28, 1, "Walerego", "Radomira", "Tomasza"),
    Ndr(29, 1, "Zdzisława", "Franciszka", "Józefa"),
    Ndr(30, 1, "Macieja", "Martyny", "Teofila"),
    Ndr(31, 1, "Marceli", "Ludwiki", "Jana"),
    Ndr(1, 2, "Brygidy", "Ignacego", "Seweryna"),
    Ndr(2, 2, "Marii", "Miłosława"),
    Ndr(3, 2, "Błażeja", "Oskara"),
    Ndr(4, 2, "Andrzeja", "Weroniki", "Joanny"),
    Ndr(5, 2, "Agaty", "Adelajdy", "Izydora"),
    Ndr(6, 2, "Doroty", "Bogdana", "Pawła"),
    Ndr(7, 2, "Ryszarda", "Teodora", "Romana"),
    Ndr(8, 2, "Hieronima", "Sebastiana", "Ireny"),
    Ndr(9, 2, "Apolonii", "Eryki", "Cyryla"),
    Ndr(10, 2, "Elwiry", "Jacka", "Scholastyki"),
    Ndr(11, 2, "Lucjana", "Olgierda", "Grzegorza"),
    Ndr(12, 2, "Eulalii", "Radosława", "Modesta"),
    Ndr(13, 2, "Grzegorza", "Katarzyny"),
    Ndr(14, 2, "Cyryla", "Metodego", "Walentego"),
    Ndr(15, 2, "Jowity", "Faustyna", "Zygfryda"),
    Ndr(16, 2, "Danuty", "Julianny", "Daniela"),
    Ndr(17, 2, "Aleksego", "Zbigniewa", "Łukasza"),
    Ndr(18, 2, "Szymona", "Konstancji", "Flawiana"),
    Ndr(19, 2, "Arnolda", "Konrada", "Marcelego"),
    Ndr(20, 2, "Leona", "Ludomira", "Zenobiusza"),
    Ndr(21, 2, "Eleonory", "Fortunata", "Roberta"),
    Ndr(22, 2, "Marty", "Małgorzaty", "Piotra"),
    Ndr(23, 2, "Romany", "Damiana", "Polikarpa"),
    Ndr(24, 2, "Macieja", "Bogusza", "Sergiusza"),
    Ndr(25, 2, "Wiktora", "Cezarego"),
    Ndr(26, 2, "Mirosława", "Aleksandra"),
    Ndr(27, 2, "Gabriela", "Anastazji"),
    Ndr(28, 2, "Romana", "Ludomira", "Lecha"),
    Ndr(1, 3, "Antoniny", "Radosława", "Dawida"),
    Ndr(2, 3, "Heleny", "Halszki", "Pawła"),
    Ndr(3, 3, "Maryny", "Kunegundy", "Tycjana"),
    Ndr(4, 3, "Łucji", "Kazimierza", "Eugeniusza"),
    Ndr(5, 3, "Adriana", "Fryderyka", "Teofila"),
    Ndr(6, 3, "Róży", "Jordana", "Agnieszki"),
    Ndr(7, 3, "Tomasza", "Perpetuy", "Felicyty"),
    Ndr(8, 3, "Beaty", "Wincentego", "Jana"),
    Ndr(9, 3, "Franciszki", "Brunona"),
    Ndr(10, 3, "Cypriana", "Marcela", "Aleksandra"),
    Ndr(11, 3, "Ludosława", "Konstantyna", "Benedykta"),
    Ndr(12, 3, "Grzegorza", "Justyna", "Alojzego"),
    Ndr(13, 3, "Bożeny", "Krystyny"),
    Ndr(14, 3, "Leona", "Matyldy", "Łazarza"),
    Ndr(15, 3, "Longina", "Klemensa", "Ludwiki"),
    Ndr(16, 3, "Izabeli", "Oktawii", "Hilarego"),
    Ndr(17, 3, "Patryka", "Zbigniewa", "Gertrudy"),
    Ndr(18, 3, "Cyryla", "Edwarda", "Boguchwały"),
    Ndr(19, 3, "Józefa", "Bogdana"),
    Ndr(20, 3, "Klaudii", "Eufemii", "Maurycego"),
    Ndr(21, 3, "Lubomira", "Benedykta"),
    Ndr(22, 3, "Katarzyny", "Bogusława"),
    Ndr(23, 3, "Pelagii", "Oktawiana", "Feliksa"),
    Ndr(24, 3, "Marka", "Gabriela", "Katarzyny"),
    Ndr(25, 3, "Marioli", "Wieäczysława", "Ireneusza"),
    Ndr(26, 3, "Larysy", "Emanyela", "Teodora"),
    Ndr(27, 3, "Lidii", "Ernesta"),
    Ndr(28, 3, "Anieli", "Sykstusa", "Jana"),
    Ndr(29, 3, "Wiktoryna", "Helmuta", "Eustachego"),
    Ndr(30, 3, "Anieli", "Kwiryna", "Leonarda"),
    Ndr(31, 3, "Beniamina", "Dobromierza", "Leonarda"),
    Ndr(1, 4, "Teodory", "Grażyny", "Ireny"),
    Ndr(2, 4, "Władysława", "Franciszka", "Teodozji"),
    Ndr(3, 4, "Ryszarda", "Pankracego", "Ingi"),
    Ndr(4, 4, "Izydora", "Wacława"),
    Ndr(5, 4, "Ireny", "Wincentego"),
    Ndr(6, 4, "Izoldy", "Celestyna", "Wilhelma"),
    Ndr(7, 4, "Rufina", "Celestyna", "Jana"),
    Ndr(8, 4, "Cezaryny", "Dionizego", "Julii"),
    Ndr(9, 4, "Marii", "Dymitra", "Heliodora"),
    Ndr(10, 4, "Michała", "Makarego"),
    Ndr(11, 4, "Filipa", "Leona"),
    Ndr(12, 4, "Juliusza", "Lubosława", "Zenona"),
    Ndr(13, 4, "Przemysława", "Hermenegildy", "Marcina"),
    Ndr(14, 4, "Bereniki", "Waleriana", "Justyny"),
    Ndr(15, 4, "Ludwiny", "Wacławy", "Anastazji"),
    Ndr(16, 4, "Kseni", "Cecylii", "Bernardety"),
    Ndr(17, 4, "Rudolfa", "Roberta"),
    Ndr(18, 4, "Bogusławy", "Apoloniusza"),
    Ndr(19, 4, "Adolfa", "Tymona", "Leona"),
    Ndr(20, 4, "Czesława", "Agnieszki", "Mariana"),
    Ndr(21, 4, "Anzelma", "Bartosza", "Feliksa"),
    Ndr(22, 4, "Kai", "Leonii", "Sotera"),
    Ndr(23, 4, "Jerzego", "Wojciecha"),
    Ndr(24, 4, "Horacego", "Feliksa", "Grzegorza"),
    Ndr(25, 4, "Marka", "Jarosława"),
    Ndr(26, 4, "Marzeny", "Klaudiusza", "Marii"),
    Ndr(27, 4, "Zyty", "Teofila", "Felicji"),
    Ndr(28, 4, "Piotra", "Walerii", "Witalisa"),
    Ndr(29, 4, "Rity", "Katarzyny", "Bogusława"),
    Ndr(30, 4, "Mariana", "Donaty", "Tamary"),
    Ndr(1, 5, "Józefa", "Jeremiasza", "Filipa"),
    Ndr(2, 5, "Zygmunta", "Atanazego", "Anatola"),
    Ndr(3, 5, "Marii", "Antoniny"),
    Ndr(4, 5, "Moniki", "Floriana", "Władysława"),
    Ndr(5, 5, "Ireny", "Waldemara"),
    Ndr(6, 5, "Judyty", "Jakuba", "Filipa"),
    Ndr(7, 5, "Gizeli", "Ludmiły", "Benedykta"),
    Ndr(8, 5, "Stanisława", "Lizy", "Wiktora"),
    Ndr(9, 5, "Bożydara", "Grzegorza", "Karoliny"),
    Ndr(10, 5, "Izydora", "Antoniny", "Symeona"),
    Ndr(11, 5, "Igi", "Miry", "Władysławy"),
    Ndr(12, 5, "Pankracego", "Dominika", "Achillesa"),
    Ndr(13, 5, "Serwacego", "Roberta", "Glorii"),
    Ndr(14, 5, "Bonifacego", "Dobiesława", "Macieja"),
    Ndr(15, 5, "Zofii", "Nadziei", "Izydora"),
    Ndr(16, 5, "Andrzeja", "Jędrzeja", "Szymona"),
    Ndr(17, 5, "Paschalisa", "Sławomira", "Weroniki"),
    Ndr(18, 5, "Eryka", "Feliksa", "Jana"),
    Ndr(19, 5, "Iwa", "Piotra", "Celestyna"),
    Ndr(20, 5, "Bazylego", "Bernardyna", "Aleksandra"),
    Ndr(21, 5, "Wiktora", "Kryspina", "Tymoteusza"),
    Ndr(22, 5, "Heleny", "Wiesławy", "Ryty"),
    Ndr(23, 5, "Iwony", "Dezyderego", "Kryspina"),
    Ndr(24, 5, "Joanny", "Zuzanny"),
    Ndr(25, 5, "Grzegorza", "Urbana", "Magdaleny"),
    Ndr(26, 5, "Filipa", "Pauliny"),
    Ndr(27, 5, "Augustyna", "Juliana", "Magdaleny"),
    Ndr(28, 5, "Jaromira", "Justa", "Justyny"),
    Ndr(29, 5, "Magdaleny", "Bogumiły", "Urszuli"),
    Ndr(30, 5, "Ferdynanda", "Karola", "Jana"),
    Ndr(31, 5, "Anieli", "Petroneli"),
    Ndr(1, 6, "Justyna", "Anieli", "Konrada"),
    Ndr(2, 6, "Marianny", "Marcelina", "Piotra"),
    Ndr(3, 6, "Leszka", "Tamary", "Karola"),
    Ndr(4, 6, "Kwiryny", "Franciszka"),
    Ndr(5, 6, "Waltera", "Bonifacego", "Walerii"),
    Ndr(6, 6, "Norberta", "Laurentego", "Bogumiła"),
    Ndr(7, 6, "Roberta", "Wiesława"),
    Ndr(8, 6, "Medarda", "Maksyma", "Seweryna"),
    Ndr(9, 6, "Pelagii", "Dominika", "Efrema"),
    Ndr(10, 6, "Bogumiła", "Małgorzaty", "Diany"),
    Ndr(11, 6, "Barnaby", "Radomiła", "Feliksa"),
    Ndr(12, 6, "Janiny", "Onufrego", "Leona"),
    Ndr(13, 6, "Lucjana", "Antoniego"),
    Ndr(14, 6, "Bazylego", "Elwiry", "Michała"),
    Ndr(15, 6, "Wita", "Jolanty"),
    Ndr(16, 6, "Aliny", "Benona", "Anety"),
    Ndr(17, 6, "Laury", "Marcjana", "Alberta"),
    Ndr(18, 6, "Marka", "Elżbiety"),
    Ndr(19, 6, "Gerwazego", "Protazego"),
    Ndr(20, 6, "Diny", "Bogny", "Florentyny"),
    Ndr(21, 6, "Alicji", "Alojzego"),
    Ndr(22, 6, "Pauliny", "Tomasza", "Jana"),
    Ndr(23, 6, "Wandy", "Zenona"),
    Ndr(24, 6, "Jana", "Danuty"),
    Ndr(25, 6, "Łucji", "Wilhelma", "Doroty"),
    Ndr(26, 6, "Jana", "Pawła"),
    Ndr(27, 6, "Maryli", "Władysława", "Cyryla"),
    Ndr(28, 6, "Leona", "Ireneusza"),
    Ndr(29, 6, "Piotra", "Pawła"),
    Ndr(30, 6, "Emilii", "Lucyny"),
    Ndr(1, 7, "Haliny", "Mariana", "Marcina"),
    Ndr(2, 7, "Jagody", "Urbama", "Marii"),
    Ndr(3, 7, "Jacka", "Anatola", "Tomasza"),
    Ndr(4, 7, "Odona", "Malwiny", "Elżbiety"),
    Ndr(5, 7, "Marii", "Antoniego"),
    Ndr(6, 7, "Gotarda", "Dominiki", "Łucji"),
    Ndr(7, 7, "Cyryla", "Estery", "Metodego"),
    Ndr(8, 7, "Edgara", "Elżbiety", "Eugeniusza"),
    Ndr(9, 7, "Lukrecji", "Weroniki", "Zenona"),
    Ndr(10, 7, "Sylwany", "Witalisa", "Antoniego"),
    Ndr(11, 7, "Olgi", "Kaliny", "Benedykta"),
    Ndr(12, 7, "Jana", "Brunona", "Bonifacego"),
    Ndr(13, 7, "Henryka", "Kingi", "Andrzeja"),
    Ndr(14, 7, "Ulryka", "Bonawentury", "Kamila"),
    Ndr(15, 7, "Henryka", "Włodzimierza", "Dawida"),
    Ndr(16, 7, "Mariki", "Benity", "Eustachego"),
    Ndr(17, 7, "Anety", "Bogdana", "Jadwigi"),
    Ndr(18, 7, "Erwina", "Kamila", "Szymona"),
    Ndr(19, 7, "Wincentego", "Wodzisława", "Marcina"),
    Ndr(20, 7, "Czesława", "Hieronioma", "Małgorzaty"),
    Ndr(21, 7, "Daniela", "Dalidy", "Wawrzyäca"),
    Ndr(22, 7, "Marii", "Magdaleny"),
    Ndr(23, 7, "Stwosza", "Bogny", "Brygidy"),
    Ndr(24, 7, "Kingi", "Krystyny"),
    Ndr(25, 7, "Walentyny", "Krzysztofa", "Jakuba"),
    Ndr(26, 7, "Anny", "Mirosławy", "Grażyny"),
    Ndr(27, 7, "Lilii", "Julii", "Natalii"),
    Ndr(28, 7, "Aidy", "Marceli", "Wiktora"),
    Ndr(29, 7, "Olafa", "Marty", "Ludmiły"),
    Ndr(30, 7, "Julity", "Piotra", "Aldony"),
    Ndr(31, 7, "Ignacego", "Lubomira", "Heleny"),
    Ndr(1, 8, "Nadii", "Justyna", "Juliana"),
    Ndr(2, 8, "Kariny", "Gustawa", "Euzebiusza"),
    Ndr(3, 8, "Lidii", "Augusta", "Nikodema"),
    Ndr(4, 8, "Dominika", "Protazego", "Jana"),
    Ndr(5, 8, "Oswalda", "Marii", "Mariana"),
    Ndr(6, 8, "Sławy", "Jakuba", "Oktawiana"),
    Ndr(7, 8, "Kajetana", "Doroty", "Sykstusa"),
    Ndr(8, 8, "Cypriana", "Emiliana", "Dominika"),
    Ndr(9, 8, "Romana", "Ryszarda", "Edyty"),
    Ndr(10, 8, "Borysa", "Filomeny", "Wawrzyńca"),
    Ndr(11, 8, "Klary", "Zuzanny", "Lecha"),
    Ndr(12, 8, "Innocentego", "Lecha", "Euzebii"),
    Ndr(13, 8, "Diany", "Hipolita", "Poncjana"),
    Ndr(14, 8, "Alfreda", "Euzebiusza", "Maksymiliana"),
    Ndr(15, 8, "Napoleona", "Stelii"),
    Ndr(16, 8, "Rocha", "Stefana", "Joachima"),
    Ndr(17, 8, "Żanny", "Mirona", "Jacka"),
    Ndr(18, 8, "Ilony", "Bronisława", "Heleny"),
    Ndr(19, 8, "Bolesława", "Juliana"),
    Ndr(20, 8, "Bernarda", "Samuela", "Sobiesława"),
    Ndr(21, 8, "Joanny", "Kazimiery", "Piusa"),
    Ndr(22, 8, "Cezarego", "Tymoteusza"),
    Ndr(23, 8, "Apolinarego", "Filipa"),
    Ndr(24, 8, "Jerzego", "Bartosza", "Haliny"),
    Ndr(25, 8, "Luizy", "Ludwika", "Józefa"),
    Ndr(26, 8, "Marii", "Aleksandra"),
    Ndr(27, 8, "Józefa", "Kolasantego"),
    Ndr(28, 8, "Patrycji", "Wyszomira", "Augustyna"),
    Ndr(29, 8, "Jana", "Sabiny", "Racibora"),
    Ndr(30, 8, "Róży", "Szczęsnego", "Feliksa"),
    Ndr(31, 8, "Ramony", "Rajmunda", "Bogdana"),
    Ndr(1, 9, "Idziego", "Bronisława"),
    Ndr(2, 9, "Stefana", "Wilhelma", "Juliana"),
    Ndr(3, 9, "Izabeli", "Szymona", "Grzegorza"),
    Ndr(4, 9, "Rozalii", "Róży"),
    Ndr(5, 9, "Doroty", "Wawrzyńca", "Teodora"),
    Ndr(6, 9, "Beaty", "Eugeniusza"),
    Ndr(7, 9, "Reginy", "Melchiora", "Domosławy"),
    Ndr(8, 9, "Marii", "Adrianny", "Serafiny"),
    Ndr(9, 9, "Ścibora", "Sergiusza", "Piotra"),
    Ndr(10, 9, "Łukasza", "Aldony", "Mścisława"),
    Ndr(11, 9, "Jacka", "Prota", "Dagny", "Hiacynta"),
    Ndr(12, 9, "Gwidona", "Radzimira", "Marii"),
    Ndr(13, 9, "Eugenii", "Aureliusza", "Jana"),
    Ndr(14, 9, "Roksany", "Bernarda", "Cypriana"),
    Ndr(15, 9, "Albina", "Nikodema", "Marii"),
    Ndr(16, 9, "Edyty", "Korneliusza", "Cypriana"),
    Ndr(17, 9, "Franciszka", "Roberta", "Justyna"),
    Ndr(18, 9, "Irmy", "Stanisława", "Ireny"),
    Ndr(19, 9, "Januarego", "Konstancji", "Teodora"),
    Ndr(20, 9, "Filipiny", "Eustachego", "Euzebii"),
    Ndr(21, 9, "Jonasza", "Mateusza", "Hipolita"),
    Ndr(22, 9, "Tomasza", "Maurycego", "Joachima"),
    Ndr(23, 9, "Tekli", "Bogusława", "Linusa"),
    Ndr(24, 9, "Gerarda", "Ruperta", "Tomiry"),
    Ndr(25, 9, "Aurelii", "Władysława", "Kleofasa"),
    Ndr(26, 9, "Wawrzyńca", "Kosmy", "Damiana"),
    Ndr(27, 9, "Wincentego", "Mirabeli", "Justyny"),
    Ndr(28, 9, "Wacława", "Tymona", "Marka"),
    Ndr(29, 9, "Michała", "Gabriela", "Rafała"),
    Ndr(30, 9, "Wery", "Honoriusza", "Hieronima"),
    Ndr(1, 10, "Danuty", "Remigiusza", "Teresy"),
    Ndr(2, 10, "Teofila", "Dionizego", "Sławomira"),
    Ndr(3, 10, "Teresy", "Heliodora", "Jana"),
    Ndr(4, 10, "Rozalii", "Edwina", "Franciszka"),
    Ndr(5, 10, "Placyda", "Apolinarego"),
    Ndr(6, 10, "Artura", "Brunona"),
    Ndr(7, 10, "Marii", "Marka", "Mirelli"),
    Ndr(8, 10, "Pelagii", "Brygidy", "Walerii"),
    Ndr(9, 10, "Amolda", "Dionizego", "Wincentego"),
    Ndr(10, 10, "Pauliny", "Danieli", "Leona"),
    Ndr(11, 10, "Aldony", "Aleksandra", "Dobromiry"),
    Ndr(12, 10, "Eustachego", "Maksymiliana", "Edwina"),
    Ndr(13, 10, "Geralda", "Edwarda", "Honorata"),
    Ndr(14, 10, "Liwii", "Kaliksta", "Bernarda"),
    Ndr(15, 10, "Jadwigi", "Teresy", "Florentyny"),
    Ndr(16, 10, "Gawła", "Ambrożego"),
    Ndr(17, 10, "Wiktora", "Marity", "Ignacego"),
    Ndr(18, 10, "Juliana", "Łukasza"),
    Ndr(19, 10, "Ziemowita", "Jana", "Pawła"),
    Ndr(20, 10, "Ireny", "Kleopatry", "Jana"),
    Ndr(21, 10, "Urszuli", "Hilarego", "Jakuba"),
    Ndr(22, 10, "Halki", "Filipa", "Salomei"),
    Ndr(23, 10, "Marleny", "Seweryna", "Igi"),
    Ndr(24, 10, "Rafała", "Marcina", "Antoniego"),
    Ndr(25, 10, "Darii", "Wilhelminy", "Bonifacego"),
    Ndr(26, 10, "Lucjana", "Ewarysta", "Damiana"),
    Ndr(27, 10, "Iwony", "Sabiny"),
    Ndr(28, 10, "Szymona", "Tadeusza"),
    Ndr(29, 10, "Euzebii", "Wioletty", "Felicjana"),
    Ndr(30, 10, "Zenobii", "Przemysława", "Edmunda"),
    Ndr(31, 10, "Urbana", "Saturnina", "Krzysztofa"),
    Ndr(1, 11, "Wszystkich Świętych"),
    Ndr(2, 11, "Bohdany", "Bożydara"),
    Ndr(3, 11, "Sylwii", "Marcina", "Huberta"),
    Ndr(4, 11, "Karola", "Olgierda"),
    Ndr(5, 11, "Elżbiety", "Sławomira", "Dominika"),
    Ndr(6, 11, "Feliksa", "Leonarda", "Ziemowita"),
    Ndr(7, 11, "Antoniego", "Żytomira", "Ernesta"),
    Ndr(8, 11, "Seweryna", "Bogdana", "Klaudiusza"),
    Ndr(9, 11, "Aleksandra", "Ludwika", "Teodora"),
    Ndr(10, 11, "Leny", "Ludomira", "Leona"),
    Ndr(11, 11, "Marcina", "Batłomieja", "Teodora"),
    Ndr(12, 11, "Renaty", "Witolda", "Jozafata"),
    Ndr(13, 11, "Mateusza", "Izaaka", "Stanisława"),
    Ndr(14, 11, "Rogera", "Serafina", "Wawrzyäca"),
    Ndr(15, 11, "Alberta", "Leopolda"),
    Ndr(16, 11, "Gertrudy", "Edmunda", "Marii"),
    Ndr(17, 11, "Salomei", "Grzegorza", "Elżbiety"),
    Ndr(18, 11, "Romana", "Klaudyny", "Karoliny"),
    Ndr(19, 11, "Seweryny", "Maksyma", "Salomei"),
    Ndr(20, 11, "Anatola", "Sędzimira", "Rafała"),
    Ndr(21, 11, "Janusza"),
    Ndr(22, 11, "Cecylii", "Wszemiły", "Stefana"),
    Ndr(23, 11, "Adelii", "Klemensa", "Felicyty"),
    Ndr(24, 11, "Flory", "Emmy", "Chryzogona"),
    Ndr(25, 11, "Erazma", "Katarzyny"),
    Ndr(26, 11, "Delfiny", "Sylwestra", "Konrada"),
    Ndr(27, 11, "Waleriana", "Wirgiliusza", "Maksyma"),
    Ndr(28, 11, "Lesława", "Zdzisława", "Stefana"),
    Ndr(29, 11, "Błażeja", "Saturnina"),
    Ndr(30, 11, "Andrzeja", "Maury", "Konstantego"),
    Ndr(1, 12, "Natalii", "Eligiusza", "Edmunda"),
    Ndr(2, 12, "Balbiny", "Bibianny", "Pauliny"),
    Ndr(3, 12, "Franciszka", "Ksawerego", "Kasjana"),
    Ndr(4, 12, "Barbary", "Krystiana", "Jana"),
    Ndr(5, 12, "Sabiny", "Krystyny", "Edyty"),
    Ndr(6, 12, "Mikołaja", "Jaremy", "Emiliana"),
    Ndr(7, 12, "Marcina", "Ambrożego", "Teodora"),
    Ndr(8, 12, "Marii", "Światozara", "Makarego"),
    Ndr(9, 12, "Wiesława", "Leokadii", "Joanny"),
    Ndr(10, 12, "Julii", "Danieli", "Bogdana"),
    Ndr(11, 12, "Damazego", "Waldemara", "Daniela"),
    Ndr(12, 12, "Dagmary", "Aleksandra", "Ady"),
    Ndr(13, 12, "Łucji", "Otylii"),
    Ndr(14, 12, "Alfreda", "Izydora", "Jana"),
    Ndr(15, 12, "Niny", "Celiny", "Waleriana"),
    Ndr(16, 12, "Albiny", "Zdzisławy", "Alicji"),
    Ndr(17, 12, "Olimpii", "Łazarza", "Floriana"),
    Ndr(18, 12, "Gracjana", "Bogusława", "Laurencji"),
    Ndr(19, 12, "Gabrieli", "Dariusza", "Eleonory"),
    Ndr(20, 12, "Bogumiły", "Dominika"),
    Ndr(21, 12, "Tomisława", "Seweryna", "Piotra"),
    Ndr(22, 12, "Zenona", "Honoraty", "Franciszki"),
    Ndr(23, 12, "Wiktorii", "Sławomiry", "Jana"),
    Ndr(24, 12, "Adama", "Ewy", "Eweliny"),
    Ndr(25, 12, "Anastazji", "Eugenii"),
    Ndr(26, 12, "Dionizego", "Szczepana"),
    Ndr(27, 12, "Jana", "Żanety", "Maksyma"),
    Ndr(28, 12, "Teofilii", "Godzisława", "Cezarego"),
    Ndr(29, 12, "Dawida", "Tomasza", "Dominika"),
    Ndr(30, 12, "Rainera", "Eugeniusza", "Irmy"),
    Ndr(31, 12, "Sylwestra", "Melanii", "Mariusza"),
)

private val nameDays = mapOf(
    "PL" to polishNameDays,
)

fun determineNamedaysFor(day: LocalDate, country: String): Set<String> {
    val countryNameDays = requireNotNull(nameDays[country.uppercase()]) { "unsupported country: $country" }
    return countryNameDays.find { it.month == day.monthNumber && it.day == day.dayOfMonth }?.names ?: emptySet()
}
